package com.allybros.jetpack_compose_games_app.entity.detail

data class GamesDetailResponse(
    val achievements_count: Int? = 0,
    val added: Int? = 0,
    val added_by_status: AddedByStatus? = null,
    val additions_count: Int? = 0,
    val alternative_names: List<String>? = null,
    val background_image: String? = "",
    val background_image_additional: String? = "",
    val creators_count: Int? = 0,
    val description: String? = "",
    val esrb_rating: EsrbRating? = null,
    val game_series_count: Int? = 0,
    val id: Int? = 0,
    val metacritic: Double? = 0.0,
    val metacritic_platforms: List<MetacriticPlatform>? = null,
    val metacritic_url: String? = "",
    val movies_count: Int? = 0,
    val name: String? = "",
    val name_original: String? = "",
    val parent_achievements_count: String? = "",
    val parents_count: Int? = 0,
    val platforms: List<Platform>? = null,
    val playtime: Int? = 0,
    val rating: Double? = 0.0,
    val rating_top: Double? = 0.0,
    val reactions: Reactions? = null,
    val reddit_count: Int? = 0,
    val reddit_description: String? = "",
    val reddit_logo: String? = "",
    val reddit_name: String? = "",
    val reddit_url: String? = "",
    val released: String? = "",
    val reviews_text_count: String? = "",
    val screenshots_count: Int? = 0,
    val slug: String? = "",
    val suggestions_count: Int? = 0,
    val tba: Boolean? = false,
    val twitch_count: String? = "",
    val updated: String? = "",
    val website: String? = "",
    val youtube_count: String? = "",
    val description_raw: String? = ""
)